// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stage.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDol9PNN_Cmdhl_QxZTQM47liYp-q1kf7Q',
    appId: '1:30513548056:web:eaead3c8afccc4e27a6c6d',
    messagingSenderId: '30513548056',
    projectId: 'mycampusinfo-d3308',
    authDomain: 'mycampusinfo-d3308.firebaseapp.com',
    storageBucket: 'mycampusinfo-d3308.firebasestorage.app',
    measurementId: 'G-V7N1D1VQWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArUUDCmSBPcUaPpdkIj_BZF-xNdytVuUw',
    appId: '1:30513548056:android:690e5fc518e4d6347a6c6d',
    messagingSenderId: '30513548056',
    projectId: 'mycampusinfo-d3308',
    storageBucket: 'mycampusinfo-d3308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_Zby_KfuZLegH99mRsvIeNXihhBhXdo',
    appId: '1:30513548056:ios:0b857780210e32817a6c6d',
    messagingSenderId: '30513548056',
    projectId: 'mycampusinfo-d3308',
    storageBucket: 'mycampusinfo-d3308.firebasestorage.app',
    iosBundleId: 'com.talentconnect.mycampusinfoApp',
  );
}
